### ISSUE TITLE
Why start from scratch?

### ISSUE THREAD

**Issue by drujensen** [luckyframework/website-old#6]
Hi Paul,

We have been working on Amber for a several years now and would love to have ThoughtBot help us.  

Is there a reason you are starting from scratch?

Take a look at http://amberframework.org

Dru

**Comment by paulcsmith** [comment]
Closing this because I've been in contact with the Amber team since this issue was released. I will likely still work on Lucky because we have some different takes on a few things, but we are sharing a lot of ideas and code, and who knows, maybe we combine efforts down the road!

I love this friendly Crystal/Amber community :D
